version: '3.5'

services:
  bot-mysql-db:
    platform: linux/amd64
    image: mysql:5.7
    container_name: bot-mysql-db
    volumes:
      - ./mysql_db:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=securerootpassword
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}

  bot:
    depends_on:
      - bot-mysql-db
    build:
      context: .docker/docker
      dockerfile: Dockerfile
    container_name: bot
    ports:
      - 9980:80
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
    volumes:
      - ./:/var/www/html
      - ./logs/bot:/var/www/html/storage/logs

  bot-pma:
    image: phpmyadmin/phpmyadmin
    container_name: bot-pma
    ports:
      - 8100:80
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_ROOT_PASSWORD=securerootpassword
      - PMA_HOST=bot-mysql-db
